baseurl: /campusmap_reports
permalink: pretty
paginate: 10
relative_permalinks: true
markdown: rdiscount
prose:
  siteurl: 'http://isegimap.github.io/campusmap_reports/'
  relativeLinks: 'http://isegimap.github.io/campusmap_reports/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "tutorials"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Tutorials"
              value: "tutorials"
            - name: "QGIS"
              value: "qgis"
            - name: "Buffer"
              value: "buffer"
            - name: "Selections"
              value: "selections"